### ISSUE TITLE
add socket.id - property

### ISSUE THREAD

**Issue by peterpeter5** [sacOO7/socketcluster-client-python#1]
At the moment at the socket-class does not save its socket-id. In the JS-implemtation the socket-id is a valid property. 
This makes it harder to talk to applications how rely on this information.

**Comment by sacOO7** [comment]
Ok, I will update the project today to add the property. Just wanted to ask, why it's harder to talk to applications? I think currently you can query server for socket-id although it doesn't exist on client side.

**Comment by peterpeter5** [comment]
I recently came along an application, which uses the socket-id in communication: https://github.com/zalmoxisus/remotedev-server/blob/v0.3/docs/API/Realtime.md

Of course in this example its not a real issue, as you can use the server without ```socket.id```. But if its present in the js-api, than its like to be used by other applications. 

I don't know how to query the server for the socket-id, but if this is possible i think its an equally valid approach. I just saw the socket-id in the info-logs (i think transmitted during the authentication-step)

**Comment by sacOO7** [comment]
Yeah, you can query it to server. If you like this client, star the repo. , share it with your dev friends. More issues are always welcome :) .

**Comment by sacOO7** [comment]
I'm closing this issue as I can't see any further problems related to client .

**Comment by sacOO7** [comment]
**UPDATE** : I have updated the client and socket.id is now accessible.
