### ISSUE TITLE
logging.basicConfig should not be called in library

### ISSUE THREAD

**Issue by leftys** [sacOO7/socketcluster-client-python#15]
Hello,

I found out that 

```
logging.basicConfig(format='%(levelname)s:%(message)s', level=logging.DEBUG)
```

in Scoketcluster.py interferes with logging settings of our application. It's really a bad practice to set-up logging inside library module. Could you remove it and leave this on caller?

Jan

**Comment by sacOO7** [comment]
Hi @leftys , I don't think it's available in the latest version of library. Can you try downloading latest version and check if it is there?

**Comment by sacOO7** [comment]
Or you can check the current source code on the master .... It's the same version as published version on pip.

**Comment by leftys** [comment]
you're right, sorry! closing

**Comment by sacOO7** [comment]
Hey no problem... Feel free to raise more issues.
