### ISSUE TITLE
Incompatibility with Python 3.X

### ISSUE THREAD

**Issue by pauljherrera** [sacOO7/socketcluster-client-python#4]
I tried to import the library on Python 3.6. I did it on Anaconda distribution and a Windows machine.

from socketclusterclient import Socketcluster

I got this error.

  File "C:\ProgramData\Anaconda3\lib\site-packages\socketclusterclient\Socketcluster.py", line 256
    print "delay"
                ^
SyntaxError: Missing parentheses in call to 'print'

I changed the Socketcluster.py on my local machine and it ran just fine. I just did:
from __future__ import print_function

And then added the parenthesis in the line 256. I think it should be compatible to Python 2 and 3.

**Comment by sacOO7** [comment]
Thank you, I will fix the bug and update the library on Pypi.

**Comment by sacOO7** [comment]
Latest library has been uploaded, please take a look.

**Comment by pauljherrera** [comment]
Thanks a lot!
