### ISSUE TITLE
Receiving the data via socketcluster-client-python

### ISSUE THREAD

**Issue by lshusharin** [sacOO7/socketcluster-client-python#5]
I have established and authenticated connection with a socketcluster server. 
Now I need to receive a data from server. I understand that I have to subscribe for a channel but how can I do it in appropriate way in code? 
What method should I use for subscribing and where should I call it?

**Comment by sacOO7** [comment]
```
import logging
from socketclusterclient import Socketcluster
logging.basicConfig(format="%s(levelname)s:%(message)s", level=logging.DEBUG)

import json

api_credentials = json.loads('{}')
api_credentials["apiKey"]="xxx"
api_credentials["apiSecret"]="xxx"


def your_code_starts_here(socket):
    ###Code for subscription
    socket.subscribe('TRADE-OK--BTC--CNY')                 # Channel to be subscribed

    def channelmessage(key, data):                         # Messages will be received here
        print ("\n\n\nGot data "+json.dumps(data, sort_keys=True)+" from channel "+key)

    socket.onchannel('TRADE-OK--BTC--CNY', channelmessage) # This is used for watching messages over channel
    
    ###Code for emit

    def ack(eventname, error, data):
        print ("\n\n\nGot ack data " + json.dumps(data, sort_keys=True) + " and eventname is " + eventname)    
    
    socket.emitack("exchanges",None, ack)  

    socket.emitack("channels", "OK", ack)  
      


def onconnect(socket):
    logging.info("on connect got called")

def ondisconnect(socket):
    logging.info("on disconnect got called")

def onConnectError(socket, error):
    logging.info("On connect error got called")

def onSetAuthentication(socket, token):
    logging.info("Token received " + token)
    socket.setAuthtoken(token)

def onAuthentication(socket, isauthenticated):
    logging.info("Authenticated is " + str(isauthenticated))
    def ack(eventname, error, data):
        print ("token is "+ json.dumps(data, sort_keys=True))
        your_code_starts_here(socket);

    socket.emitack("auth", api_credentials, ack)

if __name__ == "__main__":
    socket = Socketcluster.socket("wss://sc-02.coinigy.com/socketcluster/")
    socket.setBasicListener(onconnect, ondisconnect, onConnectError)
    socket.setAuthenticationListener(onSetAuthentication, onAuthentication)
    socket.setreconnection(False)
    socket.connect()
```
This is code for watching over a channel provided by Coinigy API. I think you should take a loot at official python doc on this repo. You can then understand most of the code.

Respective js example code is here
https://github.com/coinigy/api/blob/master/ws_example.js

**Comment by sacOO7** [comment]
Please **DO STAR THE CLIENT** :) .

**Comment by lshusharin** [comment]
I did! =) Thank's a lot. 
But where should I call the `your_code_starts_here` method?

**Comment by sacOO7** [comment]
It's already called inside onAuthentication (). If you don't have any problem running the code. I will be closing the issue :+1:

**Comment by dalakada** [comment]
Hi sac007, I tried sample code you posted here and I got no callbacks from any channels that I subscribed.

**Comment by sacOO7** [comment]
Can you post your code here? I need to take a look at it.

**Comment by rokcarl** [comment]
I did the same. @sacOO7 it's actually your code from a few comments up. Ran it but no channel prices came back as I expected (the `Got data ... from channel`).

I also [modified](https://gist.github.com/rokcarl/2e61d703d2611e2b5e2c48c46386f474) the code a bit, still the same.

**Comment by sacOO7** [comment]
Hi @rokcarl, sorry for the delay. I will definitely take a look at it 👍

**Comment by dalakada** [comment]
Hi, @rokcarl in my case it was my bad because i had made a typo in the channel names, I would suggest doublecheck your channel names.
